### ISSUE TITLE
static  assets

### ISSUE THREAD

**Issue by Tobi-De** [falcopackages/fujin#14]
add a simple configuration to serve assets on  specific path using the proxy

```toml
[webserver]
upstream = "unix//run/bookstore.sock"
static_paths = { "/static/" = "/var/www/project_name/static/", "/media/" = "/var/www/project_name/media/" }
```

for more complex scenarios, users can just export and edit the proxy config direclly
